spring.application.name=mcp.springboot

spring.main.web-application-type=none
spring.ai.mcp.server.name=aiengineer-video-server
spring.ai.mcp.server.version=0.0.1

spring.main.banner-mode=off
logging.pattern.console=